language: generic 


sudo: required
services:
  - docker

  # build context specifically where all the project files for the image can be found
before_install:
  - docker build -t jasonclerkin/react-test -f ./client/Dockerfile.dev ./client
  # - docker build myotherproject (run tests in other apps)

script:
  # default: npm test enters watch mode so doesn't exit ->CI=true (tests script eventually exists with status code of 0 or  not 0 if failed )
  - docker run -e CI=true jasonclerkin/react-test/react-test npm test
  #  docker run myother project (run tests in other apps) overide start up command with e.g. npm test

  # add on the configuration that's going to build production version of all of our projects
  # and then  push them off to Docker hub
  after_sucess:
    # dont need to pass in dockerfile as will use the default Dockerfile
    # gonna go through each of these sub folders and build images using the production Dockerfile
    - docker build -t jasonclerkin/multi-client ./client
    - docker build -t jasonclerkin/multi-nginx ./nginx
    - docker build -t jasonclerkin/multi-server ./server
    - docker build -t jasonclerkin/multi-worker ./worker
